{
    'name': 'Price_list_Extended',
    'version': '19.0.1.0.0',
    'category': 'Partner',
    'license': 'LGPL-3',
    'author': 'Tiny, Serpent Consulting Services Pvt. Ltd.',
    'website': 'https://www.serpentcs.com',
    'maintainer': 'Serpent Consulting Services Pvt. Ltd.',
    'summary': 'New feature in Price list',
    'depends': [
        'sale_management',
        'mail',
        'purchase',
        'project',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/price_list_update_log_view.xml',
        'views/product_pricelist_view.xml',
        'views/purchase_order_line_view.xml',
        'views/report_update_wizard_view.xml',
        'views/sale_order_line_update_log_view.xml',
        'views/sale_order_line_inherit_view.xml',
        'views/sale_order_line_report_wizard_view.xml',
        'views/res_company_inherit_view.xml',   
        'data/mail_template_sale_order_line_report.xml',
        'report/sale_order_line_report_template.xml',
        # 'report/purchase_order_report.xml',
        'data/sale_order_line_report_cron.xml',
    ],
    'installable': True,
}